### PR TITLE
Proposed parallel implementation

### PR DESCRIPTION
**Pull request by ojreed**
Is it good??

### CODE REVIEW

**Review by KuleenS — COMMENTED** [review]
LGTM push to main!

**Comment by ojreed** [comment]
wait its not good because there are some non-trivial conflicts btwn blocks and parallel. Can @Dendendelen take a peak. I don't want to mess with his blocks.

**Comment by KuleenS** [comment]
NVM needs to fix with dennis new push @ojreed :(

**Comment by KuleenS** [comment]
@Dendendelen you need to fix the merge conflict

**Pull request merged**
